### ISSUE TITLE
[PE-D][Tester E] add person throws error although phone number is valid

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-1/tp#146]
Description: Currently cannot add a person with a valid phone number

Steps to reproduce: add person with p/+6598765432

Expected: Person successfully added

Actual: Error message "International phone numbers..." shown

Screenshot:
![image.png](https://raw.githubusercontent.com/shawnnlimm/ped/main/files/f8d10f23-0c15-43e0-b7c6-6fa261082a68.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: shawnnlimm/ped#1

**Comment by logical-1985516** [comment]
There is no space between the country code and the phone number. This makes the phone number invalid as the country code is ambiguous. For instance, should the country code be "+6", "+65" or "+659"?
