### ISSUE TITLE
[PE-D][Tester C] Documentation flaw for `add_app` command in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-1/tp#162]
Under UG-Features `add-app`, the format of the input is put as `add_app e/EMAIL ti/TITLE [s/STATUS]`. However, in reality, for the examples given, the code is supposed to be in format `add_app e/EMAIL ti/TITLE s/STATUS` without the brackets like `add_app e/acekhoon@gmail.com ti/Quantitative Researcher`

You may consider fixing this.
![Screenshot 2024-04-05 at 4.48.16 PM.png](https://raw.githubusercontent.com/peterXGD/ped/main/files/a2aa6c33-9e47-47f2-bdf9-4d27fcd29d87.png)

Edit: for the next command the format makes all the parameters squared bracketed again. You may choose only one style good style for consistency of reading.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: peterXGD/ped#4

**Comment by logical-1985516** [comment]
The square brackets means that a particular parameter is optional. This is in accordance with the original AB3 user guide.
