### ISSUE TITLE
[PE-D][Tester D] No error shown when JSON data file is corrupted.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-1/tp#169]
**To reproduce:**
1. Open the `addressbook.json` file in `./data` folder
1. Change one of the key values to an empty string.
![image.png](https://raw.githubusercontent.com/ruijietay/ped/main/files/20762a61-5b85-431e-9e93-72811237d16b.png)
1. Launch Hirehub
1. Observe that application fails to load data without any error information.

**Expected:**
Would it be better to include form of error on the GUI when the data file is corrupted/not readable by the application? Although there might be some form of logging in the CLI, I think users would generally not check them.

**Actual:**
Application loads without any data, or error message.
![image.png](https://raw.githubusercontent.com/ruijietay/ped/main/files/28647560-72fb-41c2-abc9-e329d6bbe239.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ruijietay/ped#10

**Comment by chiralcentre** [comment]
The error should be seen in your terminal. Nonetheless, this degree of support for error handling is sufficient, per the TP constraints. Thank you for the feedback.

https://github.com/nus-cs2103-AY2324S2/forum/issues/618
