### ISSUE TITLE
[PE-D][Tester E] jobs does not allow large vacancies 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-1/tp#170]
Description: job vacancies does not have any limitations in user guide, but does not work with large values

Steps to reproduce:
1. edit_job with v/1000000

Expected: App should allow this since there is no limitations according to UG

Actual: App shows error message of Invalid command format

Screenshot:
![image.png](https://raw.githubusercontent.com/shawnnlimm/ped/main/files/02e2069f-09ed-4e6a-b3f7-152057351e0c.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: shawnnlimm/ped#7

**Comment by logical-1985516** [comment]
The screenshot shows an invalid command as there is no "v/" prefix. From my testing, the command works as expected.

**Comment by acekhoon** [comment]
Note that prefix v/ is missing, which I think the bug is invalid here. Thank you very much!
