### ISSUE TITLE
[PE-D][Tester B] Constraints not specified for `add_job`

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-1/tp#185]
No constraints mentioned for what are valid values for job title, vacancies for `add_job` command in UG.

![image.png](https://raw.githubusercontent.com/iynixil/ped/main/files/4cb85b5d-faa5-403d-9466-16b85504fa93.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: iynixil/ped#6

**Comment by chiralcentre** [comment]
I believe the domain of values for each field is intuitive enough
