### ISSUE TITLE
[PE-D][Tester B] Constraints not mentioned for `add_app` command parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-1/tp#188]
Constraints have been mentioned for how an application can only be added when the candidate/job exists, but does not specify what values `status` can take on unless user finds out by entering and invalid `add_app` command.

Suggestion:
Include a bullet point under `add_app` in the UG to explain what values `STATUS` can take on.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: iynixil/ped#9

**Comment by chiralcentre** [comment]
settled with Yan Jie's PR
