### ISSUE TITLE
[PE-D][Tester D] Command keywords could be shortened and simplified

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-1/tp#193]
**To reproduce:**
1. Open Hirehub
1. Perform any command (generally those that requires an underscore, or have two words)

**Expected:**
Given that the application has 23 commands, would it be better to shorten the commands so that it is optimised for the user's typing experience? 

For example, `search_job` requires the user to enter two words and one underscore, which is a character that requires the use of the shift key. Would it be better to change it to something that still uniquely identifies this command, like `sj`?

**Actual:**
Currently, I feel that the commands are rather long and can be shortened.
I have attached the list of commands in the UG for easier reference.

![image.png](https://raw.githubusercontent.com/ruijietay/ped/main/files/37b6ddc7-676e-4db0-b94b-9de1211bb5b9.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ruijietay/ped#17

**Comment by chiralcentre** [comment]
with all due respect, we wholeheartedly disagree with your proposed alternative.
